### ISSUE TITLE
Add exception handling around setAttribute

### ISSUE THREAD

**Issue by MikeKlemarewski** [mobify/mobifyjs#101]
Port this fix (https://github.com/mobify/portal_app/pull/1570) back into mobify.js

Add testing (this markup will make it break unless we have proper exception handling):

<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"
<link rel="stylesheet" href="">

**Comment by jansepar** [comment]
Added to 1.1: https://github.com/mobify/mobifyjs/blob/v1.1/api/extractDOM.js#L60
And 2.0: https://github.com/mobify/mobifyjs/blob/v2.0/src/capture.js#L141
