### ISSUE TITLE
Page rendering is slower with JazzCat

### ISSUE THREAD

**Issue by noahadams** [mobify/mobifyjs#106]
Device: Samsung Infuse (Android OS 2.3.6), Galaxy S (Android 2.3.3), iPhone 3GS (iOS 6.1.1), iPhone 4S (iOS 6.0)
Original URL: http://www.epicurious.com/recipes/food/views/Mushroom-Leek-and-Fontina-Frittata-51143040

On the specified page we include almost all of Javascripts (keep about 30 external and 45 inline scripts, combining all of them with JazzCat) joining the remaining scripts with  JazzCat. On Samsung Infuse though script loading time increases when using combineScripts().

Measured time from html header render till window.onload() event:
Infuse: 26 sec. with JazzCat and 10 sec. without
iPhone 3GS: 18sec. with JazzCat and 10sec. without
iPhone 4S: 5.7sec. with JazzCat and 3.0sec. without

The time doesn't change significantly whenever JazzCat request is cached and no new connection is made to it on page load, but depends on the amount of scripts combined with JazzCat: the more scripts, the more noticeable the difference is.

Based on this Roman assumed that the issue might be caused by slow data-url parsing on these devices.
Do you think you could try reproduce the issue with a synthetic test and fix JazzCat performance for this device?

**Comment by jansepar** [comment]
This has been solved in v2.0 by no longer using data-uris. This change has not been backported in v1.1 though. I will leave this ticket open until it is, or until we deem the backport unnecessary.

**Comment by noahadams** [comment]
It's in 1.1: https://github.com/mobify/mobifyjs/commit/73106a4b18860567485a86f9258a7f75272dd948

https://github.com/mobify/mobifyjs/pull/110

We can close this.
