### ISSUE TITLE
document.readyState == 'interactive'  is invalid DOM ready test in IE10

### ISSUE THREAD

**Issue by shogun70** [mobify/mobifyjs#136]
This relates to a bug in the v2.0 branch.

`/complete|interactive/.test(document.readyState)` and `document.onreadystatechange` are not reliable as DOM ready tests. All versions of IE can have `interactive` state before the DOM is fully loaded. Also, `readystatechange` can fire before the DOM is fully loaded. 

I have written an exploratory test which is sufficient to confirm this bug.

https://gist.github.com/shogun70/5388420

The jQuery project also has a bug report - 
[document ready is fired too early on IE 9/10](http://bugs.jquery.com/ticket/12282) 
and a "fix" - 
[sometimes IE10 and lower have document.readyState == "interactive" way too early](https://github.com/jquery/jquery/pull/901)

domReady also has a report and fix - 
[Add Guard for invalid readyState in IE9 and IE10](https://github.com/ded/domready/pull/17)

**Comment by shogun70** [comment]
Also, Opera doesn't fire the `readystatechange` event on `document`. 

CORRECTION: document.onreadystatechange fires **after** window.onload. 
I've updated the test:
https://gist.github.com/shogun70/5388420

**Comment by jansepar** [comment]
@shogun70 thanks for the test case! I will look into this and come up with the appropriate fix asap!

**Comment by shogun70** [comment]
Unlike `DOMContentLoaded` and `readystatechange`, `window.onload` is supported on all recent and almost all older browsers. When **mobify.js** is able to run on older browsers then a `window.onload` solution won't need to be updated. 

Because there is no content, images or styles to download and / or render, I would assume that `window.onload` is not significantly later than any other event that could be used.
