### ISSUE TITLE
Breaks browser history on IE, Firefox, Opera

### ISSUE THREAD

**Issue by shogun70** [mobify/mobifyjs#137]
On IE, Firefox and Opera, the `document.open(); document.write(); document.close()` call seems to add a new browser history entry with the same URL. 

After this occurs, clicking the browser back-button will return to the previous history item which is still the current URL. 

On IE and FIrefox this results in the current page reloading, the boot-script and mobify re-executing, `document.open()/write()/close()` being called and thus back to where we started. You can't leave the current page by clicking the back-button. 

Opera however, restores the state of the page before `open()/write()/close()` - this is just a blank page. Clicking the back-button once more will return to the real previous page.

**Comment by jansepar** [comment]
Hi @shogun70, thanks for filing this! After doing some research, it seems like doing this fixes the back button for Firefox:

document.open("text/html", "replace");

I still have to do some testing on the other browsers you mentioned.

**Comment by shogun70** [comment]
Thanks @jansepar. I did not know that. 

This fix seems fine for IE10, and I guess Opera can be ignored until the Webkit rebase - Opera 13??

**Comment by shogun70** [comment]
@jansepar I saw that the patch for this issue only updates the `document.open()` call in `render()`. Shouldn't this also be done for `restore()`?

**Comment by jansepar** [comment]
Yes. Yes it should :)

**Comment by shogun70** [comment]
Also, there currently isn't a fix for Opera. Should the boot-script be changed to reject Opera?

**Comment by jansepar** [comment]
I have a solution that would work specifically for Opera:

```
history.back = function(){history.go(-2)};
```

**Comment by jansepar** [comment]
Hmmm, executing `history.back()` works, and I assumed that would override the back button, but that isn't the case.

**Comment by jansepar** [comment]
Opera Next does not have the back button problem, now that it is powered by Blink. Since the back button is no longer a problem in IE, Firefox, and the latest Opera, I am closing this ticket.
