### ISSUE TITLE
image resize client url rewriting apparently broken on firefox

### ISSUE THREAD

**Issue by noahadams** [mobify/mobifyjs#23]
resulting in paths of the form `/%22http://static.beyondtherack.com/collateral/messecaplomo/splash_banner_messecaplomo.jpg%22` in the image resize server logs, which is not a valid request, causing a 400 and no image to display. 

Opera Mini on iPhone is having similar problems. 

Currently investigating with Firefox on Android

**Comment by rrjamie** [comment]
%22 is "?

Getting quotes from .attr() maybe?

**Comment by noahadams** [comment]
Yeah, this might have to do with the "custom" use of imageresizer (that is to say without using the API) on BTR, tests are passing on Firefox 14 desktop, firefox 14 beta mobile and Opera desktop

**Comment by rrjamie** [comment]
This was (now gone) on BTR:

```
 var original = '//imageresize.mobify.com/' + $(this).children('span').css('background-image').slice(4, -1);
```

**Comment by johnboxall** [comment]
Like @rrjamie mentioned, this was an issue w/ the caller code.

Firefox:

```
$('button[name=_submit]').css('background-image')
>>> "url(\"https://www.beyondtherack.com/images/button-large-black2.png\")"
```

Chrome:

```
$('button[name=_submit]').css('background-image')
>>> "url(https://www.beyondtherack.com/images/button-large-black2.png)"
```

@noahadams can you please note this on the docs.
