### ISSUE TITLE
swipe on carousel broken on Safari mobile iOS 8.0

### ISSUE THREAD

**Issue by iteratelance** [mobify/mobifyjs#286]
Go to this page: https://www.mobify.com/mobifyjs/modules/carousel/

Carousel will only go to first image and then become stuck.  Swipe will no longer take you backward or forward after first swipe.

I've confirmed that this bug exist in iOS 8.0 & 8.0.2

**Comment by jansepar** [comment]
So, the carousel on this page has actually been forked and moved to a completely separate repo. I've added a note to actually take down this page :)

If you could have a look at our latest carousel, let us know if the bug exists there:

https://mobify.github.io/scooch/

If it does have the bug, it would be great if you file it here: https://github.com/mobify/scooch

Thanks for reporting!
