### ISSUE TITLE
Not working with iPhone 6 (+ Plus)

### ISSUE THREAD

**Issue by ghost** [mobify/mobifyjs#287]
Hello,

Just purchased iPhone 6 Plus and tested carousel on my website and and with your examples. You can only slide to the next slide once and then the slider will get absolutely stuck - cannot slide anywhere after that. Tested on latest Safari and latest Google Chrome. Obviously it works on other devices just perfect.

If there is any way to pull out some javascript debug reports or anything out of the phone please let me know and I will gladly help you out.

Best regards,
Petro Mäntylä

**Comment by jansepar** [comment]
So, the carousel on this page has actually been forked and moved to a completely separate repo. I've added a note to actually take down this page :)

If you could have a look at our latest carousel, let us know if the bug exists there:

https://mobify.github.io/scooch/

If it does have the bug, it would be great if you file it here: https://github.com/mobify/scooch

Thanks for reporting!
