### ISSUE TITLE
Error with the new tag Picture

### ISSUE THREAD

**Issue by Cronos87** [mobify/mobifyjs#294]
Hello,

Chrome 38 has implemented the new tag picture, thus with Mobify I get this error:

`<source src> with a <picture> parent is invalid and therefore ignored. Please use <source srcset> instead.`

You can see the error on your demo page: http://cdn.mobify.com/mobifyjs/examples/resizeImages-picture-element/index.html

Thank you.

**Comment by jansepar** [comment]
@Cronos87 thanks for filing the bug! I'll have to integrate the latest picturefill polyfill into mobifyjs. Should be able to get to that within a few days!

**Comment by jansepar** [comment]
Opened a PR to fix this that I'm getting some team members to look at:

https://github.com/mobify/mobifyjs/pull/295

**Comment by jansepar** [comment]
This issue has been resolved in 2.0.16. Thanks again for the bug report :)

**Comment by Cronos87** [comment]
Thanks to you for the quick fix ;)
