### ISSUE TITLE
When to enable/disable debugging mode

### ISSUE THREAD

**Issue by johnboxall** [mobify/mobifyjs#33]
How to enable / disable debugging mode

Right now, debugging is activated based on whether the `mobify-path` cookie is set to a non-empty value. 

With the new opensource tag, `mobify-path` is not set in development.

You could enable it by setting a cookie but that's kind of a pain.

We could:
1. Check for `#mobify-debug=1` on the page and set the cookie / enable it if found. We could then encourage people to add it to their URL to activate debugging
2. Add another parameter to Cauldron compilation for @production, and set debugging to true if the file is being compiled in non-production mode.

**Comment by jansepar** [comment]
+1 for #2. The question then becomes, when do we give users the option to enable production mode when compiling? I would say default production off in the development server, and default on for push (with the ability to toggle both with command line params).

**Comment by johnboxall** [comment]
A note, that because of the order files are compiled in, it's actually possible today to activate debugging mode with the OST by using `#mobify-path=1`
