### ISSUE TITLE
Provide pure javascript implementation of url absolutification

### ISSUE THREAD

**Issue by noahadams** [mobify/mobifyjs#8]
for use with $.fn.resizeImages() because the DOMy way is slow when done in numbers. Also, use this for absolutification with combo.

**Comment by noahadams** [comment]
Consider: https://gist.github.com/1088850 and http://code.google.com/p/js-uri/

**Comment by johnboxall** [comment]
Re. https://github.com/mobify/mobifyjs/commit/9882642ad711bd7d90a9f8b447fa23cf12408d1f

Though it would be nice to include a full URL parser, it's not nessecary to solve this issue.

Our requirement is to absolutify the `src` property of `<script>` and `<img>` tags.

To satisfy this, we only need to ensure the reference is not already absolute and then join the 'base':

http://jsperf.com/make-url-absolute-dom-vs-js/2

**Comment by noahadams** [comment]
Also need to handle ./ and ../

**Comment by noahadams** [comment]
Also, for later reference, the property `document.baseURI` provides a `<base>` sensitive correct base URI for relative URIs in the document on iOS 3, Blackberry OS 6 and Android 2.1.

http://www.w3.org/TR/DOM-Level-3-Core/core.html#baseURIs-Considerations

**Comment by noahadams** [comment]
full url parsing is JS tends to be outperformed by the anchor element method, and less than full parsing isn't enough in a lot of situations..
