### ISSUE TITLE
Accordion module is broken in Chrome 26 and Firefox 18

### ISSUE THREAD

**Issue by tedtate** [mobify/mobifyjs#96]
Browsers:

Chrome 26 (Chrome dev channel - http://www.chromium.org/getting-involved/dev-channel)
Firefox 18.0.2 (Release)

Steps to reproduce:

1) Go to http://www.mobify.com/mobifyjs/modules/accordion/
2) Open an accordion
3) Close that accordion
4) Attempt to open that accordion again

Result:

The accordion fails to open. Also, when the accordion is fully closed the accordion is pushing page content further down the page then it should.

**Comment by tedtate** [comment]
Note: Safari 6 seems to work fine.

**Comment by noahadams** [comment]
fixed by #97
